name: "ğŸ“¢ Cáº¢NH BÃO AN NINH â€“ ÄÆ°á»£c gá»­i bá»Ÿi ElastAlert"
type: any

index: "suricata-alert-*"

filter:
  - term:
      event_type: "alert"

realert:
  seconds: 0

alert:
  - ms_teams

ms_teams_webhook_url: "https://actvneduvn.webhook.office.com/webhookb2/6d34819c-97db-4485-b31c-da14d2153e88@0aa16d8a-a396-4e21-aa14-2a68a45786bc/IncomingWebhook/1df47d12344c4f9babee448dc67909a6/39850777-0e86-41f0-b8a9-d9c2be4a150b/V2YSt4ITGVYQzKgGmQRUiz7AV3l5OiBwvGCpcVDnbDggM1"

alert_text_type: alert_text_only
alert_text: |
  ğŸ“¢ *Há»‡ thá»‘ng Ä‘Ã£ phÃ¡t hiá»‡n hoáº·c ngÄƒn cháº·n má»™t hÃ nh vi táº¥n cÃ´ng tiá»m áº©n*

  | ğŸ·ï¸ TrÆ°á»ng dá»¯ liá»‡u        | ğŸ§¾ GiÃ¡ trá»‹                                 |
  |--------------------------|--------------------------------------------|
  | ğŸ•’ **Thá»i gian**         | {14}                                       |
  | ğŸ§¾ **Rule**              | {0}                                        |
  | ğŸ“ **Loáº¡i táº¥n cÃ´ng**     | {1}                                        |
  | âš  **Má»©c Ä‘á»™**            | {2}                                        |
  | ğŸš¨ **HÃ nh Ä‘á»™ng**         | {3}                                        |
  | ğŸŒ **Nguá»“n**             | {4}:{5}                                    |
  | ğŸ¯ **ÄÃ­ch**              | {6}:{7}                                    |
  | ğŸ›œ **Giao thá»©c**         | {8}                                        |
  | ğŸ“¡ **á»¨ng dá»¥ng**          | {9}                                        |
  | ğŸŒ **Host**              | {10}                                       |
  | ğŸ“ **URL**               | {11}                                       |
  | ğŸ§­ **User-Agent**        | {12}                                       |
  | ğŸ“ **Vá»‹ trÃ­ nguá»“n**      | {13}                                       |

alert_text_args:
  - suricata_signature
  - suricata_category
  - suricata_severity
  - suricata_action
  - suricata_src_ip
  - suricata_src_port
  - suricata_dest_ip
  - suricata_dest_port
  - suricata_proto
  - suricata_app_proto
  - suricata_http_hostname
  - suricata_http_url
  - suricata_http_user_agent
  - suricata_src_geo.geo.country_name
  - vn_timestamp
